# Leviton Cloud Services API model LoopBackAuth.
# Auto-generated by api_scraper.py.
#
# Copyright 2017 Tim Lyakhovetskiy <tlyakhov@gmail.com>
#
# This code is released under the terms of the MIT license. See the LICENSE
# file for more details.
from homeauto.api_decora.decora_wifi.base_model import BaseModel


class LoopBackAuth(BaseModel):
    def __init__(self, session, model_id=None):
        super(LoopBackAuth, self).__init__(session, model_id)

